[linux_base]
extends = portduino_base
build_flags = ${portduino_base.build_flags}
  -I variants/linux
  -I /usr/include
board = cross_platform
board_level = extra
lib_deps = 
  ${portduino_base.lib_deps}
  melopero/Melopero RV3028@^1.1.0

build_src_filter = ${portduino_base.build_src_filter}
  +<../variants/linux>
  -<helpers/esp32/*.cpp>
  -<helpers/nrf52/*.cpp>
  -<helpers/stm32/*.cpp>
  -<helpers/bridges/ESPNowBridge.cpp>
  -<helpers/*/*Display.cpp>

[env:linux]
extends = linux_base
; The pkg-config commands below optionally add link flags.
; the || : is just a "or run the null command" to avoid returning an error code
build_flags = ${linux_base.build_flags}
  !pkg-config --cflags --libs libbsd-overlay --silence-errors || :

[env:linux_repeater]
extends = linux_base
build_flags =
  ${linux_base.build_flags}
  -D ADVERT_NAME='"Linux Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${linux_base.build_src_filter}
  +<../examples/simple_repeater>

lib_deps =
  ${linux_base.lib_deps}

[env:rpi_zero_2_repeater]
extends = env:linux_repeater
build_flags =
  ${env:linux_repeater.build_flags}
  -D USE_CUSTOM_SX1262_WRAPPER
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D LORA_SPIDEV='"spidev0.1"'
  -D P_LORA_DIO_0=0
  -D P_LORA_DIO_1=0  ; LORA IRQ pin
  -D P_LORA_NSS=0    ; LORA SS pin
  -D P_LORA_RESET=0  ; LORA RST pin
  -D P_LORA_BUSY=0   ; LORA Busy pin
  -D P_LORA_SCLK=0   ; LORA SCLK pin
  -D P_LORA_MISO=0   ; LORA MISO pin
  -D P_LORA_MOSI=0   ; LORA MOSI pin
  -D SX126X_POWER_EN=37
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1

lib_deps =
  ${env:linux_repeater.lib_deps}
