[linux_base]
extends = portduino_base
build_flags = ${portduino_base.build_flags}
  -I variants/linux
  -I /usr/include
board = cross_platform
board_level = extra
lib_deps = 
  ${portduino_base.lib_deps}
  melopero/Melopero RV3028@^1.1.0

build_src_filter = ${portduino_base.build_src_filter}
  +<../variants/linux>
  -<helpers/esp32/*.cpp>
  -<helpers/nrf52/*.cpp>
  -<helpers/stm32/*.cpp>
  -<helpers/bridges/ESPNowBridge.cpp>
  -<helpers/*/*Display.cpp>

[env:linux]
extends = linux_base
; The pkg-config commands below optionally add link flags.
; the || : is just a "or run the null command" to avoid returning an error code
build_flags = ${linux_base.build_flags}
  !pkg-config --cflags --libs libbsd-overlay --silence-errors || :

[env:linux_repeater]
extends = linux_base
build_flags =
  ${linux_base.build_flags}

build_src_filter = ${linux_base.build_src_filter}
  +<../examples/simple_repeater>

lib_deps =
  ${linux_base.lib_deps}

[env:rpi_zero_2_repeater]
extends = env:linux_repeater
build_flags =
  ${env:linux_repeater.build_flags}
  -g -O0 -Wall -Wextra

  -D ADVERT_NAME='"Linux Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D USE_CUSTOM_SX1262_WRAPPER
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
#  -D LORA_SPIDEV='"/dev/spidev0.1"'
#  -D P_LORA_DIO_0=27
#  -D P_LORA_NSS=7    ; LORA SS pin 7
##  -D P_LORA_NSS=-1    ; LORA SS pin 7
#  -D P_LORA_RESET=19  ; LORA RST pin 19
##  -D P_LORA_BUSY=24   ; LORA Busy pin
#  -D P_LORA_BUSY=-1   ; LORA Busy pin
#  -D P_LORA_SCLK=11   ; LORA SCLK pin
#  -D RADIOLIB_DEBUG_BASIC=1
#  -D RADIOLIB_DEBUG_SPI=1
  -D LORA_SPIDEV='"/dev/spidev0.0"'
  -D P_LORA_DIO_0=22
  -D P_LORA_NSS=-1    ; LORA SS pin 7
  -D P_LORA_RESET=13  ; LORA RST pin 19
  -D P_LORA_BUSY=-1   ; LORA Busy pin
#  -D P_LORA_SCLK=11   ; LORA SCLK pin
#  -D P_LORA_DIO_1=27  ; LORA IRQ pin 27
#  -D P_LORA_MISO=0   ; LORA MISO pin
#  -D P_LORA_MOSI=0   ; LORA MOSI pin
  -D SX126X_POWER_EN=37
#  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8f
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D LORA_FREQ=869.618f
  -D LORA_BW=62.5f
  -D LORA_SF=8
  -D LORA_CR=8
    -DRADIOLIB_EXCLUDE_CC1101=1
    -DRADIOLIB_EXCLUDE_NRF24=1
    -DRADIOLIB_EXCLUDE_RF69=1
    -DRADIOLIB_EXCLUDE_SX1231=1
    -DRADIOLIB_EXCLUDE_SX1233=1
    -DRADIOLIB_EXCLUDE_SI443X=1
    -DRADIOLIB_EXCLUDE_RFM2X=1
    -DRADIOLIB_EXCLUDE_AFSK=1
    -DRADIOLIB_EXCLUDE_BELL=1
    -DRADIOLIB_EXCLUDE_HELLSCHREIBER=1
    -DRADIOLIB_EXCLUDE_MORSE=1
    -DRADIOLIB_EXCLUDE_RTTY=1
    -DRADIOLIB_EXCLUDE_SSTV=1
    -DRADIOLIB_EXCLUDE_AX25=1
    -DRADIOLIB_EXCLUDE_DIRECT_RECEIVE=1
    -DRADIOLIB_EXCLUDE_BELL=1
    -DRADIOLIB_EXCLUDE_PAGER=1
    -DRADIOLIB_EXCLUDE_FSK4=1
    -DRADIOLIB_EXCLUDE_APRS=1
    -DRADIOLIB_EXCLUDE_LORAWAN=1

lib_deps =
  ${env:linux_repeater.lib_deps}
